# Generated by Django 3.2.3 on 2021-05-23 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('SH', 'shopping'), ('PY', 'paying'), ('FI', 'finished'), ('RF', 'refunded')], default='SH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='user creation date')),
                ('user_dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('image', models.ImageField(blank=True, default=None, upload_to='', verbose_name='Cover')),
                ('price', models.FloatField(verbose_name='Selling price ($)')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('selling', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.cart')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.user'),
        ),
    ]
